defmodule GradingClient do
  @moduledoc """
  Module used for checking answers to questions.
  """

  @doc """
  Checks the answer to a question.
  """

  @spec check_answer(any(), any(), any()) :: :correct | {:incorrect, String.t() | nil}
  def check_answer(answer, module_id, question_id) do
    GradingClient.Answers.check(module_id, question_id, answer)
  end

  @doc """
  Checks the answer to a question and prints feedback, so learners can
  evaluate their own answers from within a Livebook.

  This is the function called by the source generated by graded cells.
  """
  @spec grade(any(), any(), any()) :: :correct | :incorrect
  def grade(answer, module_id, question_id) do
    case check_answer(answer, module_id, question_id) do
      :correct ->
        IO.puts(IO.ANSI.format([:green, "Correct!"]))
        :correct

      {:incorrect, nil} ->
        IO.puts(IO.ANSI.format([:red, "Incorrect."]))
        :incorrect

      {:incorrect, help_text} ->
        IO.puts(IO.ANSI.format([:red, "Incorrect: ", :reset, help_text]))
        :incorrect
    end
  end
end
